### ISSUE TITLE
Property toggling replaces the wrong substring

### ISSUE THREAD

**Issue by sliminality** [sarahlim/chrome-remote-css#10]
If we are toggling `color: #000;` in the following style:
```css
.foo {
  /* border-color: #000; */
  color: #000;
  margin-bottom: 35px;
}
```
The `_toggleStyle` algorithm will call `currentStyleText.replace(currentPropertyText, newPropertyText)`, which incorrectly selects the first substring in the style, and results in
```css
.foo {
  /* border-/* color: #000; */ */
  color: #000;
  margin-bottom: 35px;
}
```
which fails to parse.
